/* ════════════════════════════════════════════════════
   EHSAAS — player.js
   Playback engine : HTML5 <audio> element ONLY.

   ── HOW TRACKS ARE LOADED ──────────────────────────
   Tracks are fetched automatically from the server.
   Just drop MP3 files into audio/<theme>/ folders
   and refresh the browser — no code changes needed.

   Run the server first:
     node server.js
   Then open: http://localhost:3000

   ── FOLDER STRUCTURE ───────────────────────────────
   web photo/
   └── audio/
       ├── midnight/   ← drop MP3s here
       ├── priyanka/   ← drop MP3s here
       ├── dawn/
       ├── forest/
       ├── sepia/
       └── ocean/
════════════════════════════════════════════════════ */
'use strict';

/* ─── THEMES ──────────────────────────────────────── */
const THEMES = [
  { id: 'midnight', icon: '🌙', label: 'Midnight',    title: 'Ehsaas',   sub: '"Kuch toh hai tujhse raabta..."' },
  { id: 'dawn',     icon: '🌅', label: 'Golden Dawn', title: 'Ujaala',   sub: '"Naye din ki shuruat..."' },
  { id: 'forest',   icon: '🌿', label: 'Forest Mist', title: 'Sukoon',   sub: '"Happy mood ke liye happy song..."' },
  { id: 'sepia',    icon: '🎞️', label: 'Sepia Film',  title: 'Yaadein',  sub: '"Still searching you..."' },
  { id: 'ocean',    icon: '🌊', label: 'Deep Ocean',  title: 'Lehren',   sub: '"Doob jaata hoon..."' },
  { id: 'priyanka', icon: '🫶🏻', label: 'Priyanka',   title: 'Priyanka', sub: '"Kuch to hai tujhse raabta..."' },
];

/* ─── TRACK DATA (populated from server at startup) ─ */
let THEME_TRACKS = {
  midnight: [], dawn: [], forest: [], sepia: [], ocean: [], priyanka: [],
};

/* ─── WORKING TRACK LIST (set at runtime) ────────── */
let TRACKS = [];

/* ═══════════════════════════════════════════════════
   FETCH TRACKS
   ─────────────────────────────────────────────────
   Tries two sources in order:

   1. GET /tracks  — local python server (server.py)
      Scans folders live. Works on localhost only.

   2. GET tracks.json — static file
      Generated by generate_tracks.py.
      Works on localhost AND on GitHub Pages.

   How to use:
   ─ Locally  : run  python3 server.py
   ─ GitHub   : run  python3 generate_tracks.py
                then  git add tracks.json && git push
═══════════════════════════════════════════════════ */
async function fetchTracks() {
  /* ── Try 1: live server endpoint ── */
  try {
    const res = await fetch('/tracks', { cache: 'no-store' });
    if (res.ok) {
      const data = await res.json();
      for (const theme of Object.keys(data)) {
        THEME_TRACKS[theme] = data[theme];
      }
      const total = Object.values(THEME_TRACKS).flat().length;
      console.log(`Ehsaas: loaded ${total} tracks from /tracks (live server)`);
      return;
    }
  } catch (_) {
    /* server not running — fall through to tracks.json */
  }

  /* ── Try 2: static tracks.json (GitHub Pages / file open) ── */
  try {
    const res = await fetch('tracks.json', { cache: 'no-store' });
    if (res.ok) {
      const data = await res.json();
      for (const theme of Object.keys(data)) {
        THEME_TRACKS[theme] = data[theme];
      }
      const total = Object.values(THEME_TRACKS).flat().length;
      console.log(`Ehsaas: loaded ${total} tracks from tracks.json (static)`);
      return;
    }
  } catch (_) { /* no tracks.json either */ }

  /* ── Both failed: show empty state ── */
  console.warn(
    'Ehsaas: could not load tracks.\n' +
    'Locally  → run: python3 server.py\n' +
    'GitHub   → run: python3 generate_tracks.py  then push tracks.json'
  );
}

/* ═══════════════════════════════════════════════════
   STATE
═══════════════════════════════════════════════════ */
let currentIdx     = 0;
let isPlaying      = false;
let isShuffle      = false;
let repeatMode     = 0;      // 0=off  1=all  2=one
let isMuted        = false;
let volume         = 0.8;
let liked          = new Set();
let queue          = [];
let themeIdx       = 0;
let currentThemeId = 'midnight';
let isDragging     = false;
let queueOpen      = false;

/* ─── PLAYBACK CONTROL STATE ──────────────────────────
   playPromise  — holds the current audio.play() Promise
                  so we can await it before pause/src-change.
   trackGen     — incremented every time loadTrack() is called.
                  Each audio event listener captures the gen
                  value at the moment it was registered.
                  If the gen has advanced by the time the event
                  fires, the event belongs to a stale track
                  and is silently discarded — preventing stale
                  metadata / ended events from corrupting the
                  new track's UI.
   isLoadingAudio — true while we're waiting for canplay;
                  drives the loading spinner on the disc/button.
──────────────────────────────────────────────────── */
let playPromise    = null;
let trackGen       = 0;       // ← race-condition guard
let isLoadingAudio = false;

/* ═══════════════════════════════════════════════════
   DOM REFERENCES
═══════════════════════════════════════════════════ */
let audio, playBtn, playIco, shufBtn,
    repeatBtn, repeatIco, muteBtn, muteIco,
    volSlider, likeBtn,
    pFill, pDot, pBar,
    tCur, tTot,
    tName, tArt,
    aImg, aDisc,
    trkList, trkCnt,
    qList, qCnt, qEmpty, qSec,
    hTitle, hSub, heroBg,
    tgBtn, tgIco, tgLbl, tgDrop;

/* ═══════════════════════════════════════════════════
   INIT
═══════════════════════════════════════════════════ */
function init() {
  /* Resolve all DOM refs once the document is ready */
  audio     = document.getElementById('audioPlayer');
  playBtn   = document.getElementById('playBtn');
  playIco   = document.getElementById('playIcon');
  shufBtn   = document.getElementById('shuffleBtn');
  repeatBtn = document.getElementById('repeatBtn');
  repeatIco = document.getElementById('repeatIcon');
  muteBtn   = document.getElementById('muteBtn');
  muteIco   = document.getElementById('muteIcon');
  volSlider = document.getElementById('volSlider');
  likeBtn   = document.getElementById('likeBtn');
  pFill     = document.getElementById('progressFill');
  pDot      = document.getElementById('progressDot');
  pBar      = document.getElementById('progressBar');
  tCur      = document.getElementById('timeCur');
  tTot      = document.getElementById('timeTotal');
  tName     = document.getElementById('currentTrackName');
  tArt      = document.getElementById('currentArtist');
  aImg      = document.getElementById('albumImg');
  aDisc     = document.getElementById('albumArt');
  trkList   = document.getElementById('trackList');
  trkCnt    = document.getElementById('trackCount');
  qList     = document.getElementById('queueList');
  qCnt      = document.getElementById('queueCount');
  qEmpty    = document.getElementById('queueEmpty');
  qSec      = document.getElementById('queueSection');
  hTitle    = document.getElementById('heroTitle');
  hSub      = document.getElementById('heroSub');
  heroBg    = document.getElementById('heroBg');
  tgBtn     = document.getElementById('themeToggle');
  tgIco     = document.getElementById('themeIcon');
  tgLbl     = document.getElementById('themeLabel');
  tgDrop    = document.getElementById('themeDropdown');

  /* Defensive: audio element is mandatory */
  if (!audio) {
    console.error('Ehsaas: #audioPlayer element not found — player cannot start.');
    return;
  }

  audio.volume = volume;
  audio.muted  = isMuted;
  if (volSlider) volSlider.value = Math.round(volume * 100);

  /* Album image fallback */
  if (aImg) {
    aImg.addEventListener('error', () => { aImg.style.opacity = '0'; });
    aImg.addEventListener('load',  () => { aImg.style.opacity = '1'; });
  }

  bindAudioEvents();
  bindProgressDrag();
  bindKeyboard();
  bindParallax();

  updateMuteUI();
  updateRepeatUI();
  if (shufBtn) shufBtn.classList.toggle('active', isShuffle);

  /* ── Fetch tracks from server, then load the theme ──
     fetchTracks() fills THEME_TRACKS from /tracks API.
     Once done, loadThemeTracks() shows the songs.
     If the server is unreachable the player still
     starts — themes just show "No songs yet".          */
  fetchTracks().then(() => {
    loadThemeTracks('midnight');
  });
}

/* ═══════════════════════════════════════════════════
   WAIT-FOR-PAUSE HELPER
   Resolves any in-flight play() Promise, then pauses.
   Always returns a Promise so callers can await it.
   This prevents the "play interrupted" DOMException
   that fires when you call pause() before play() resolves.
═══════════════════════════════════════════════════ */
function waitForPause() {
  if (!audio) return Promise.resolve();
  if (playPromise !== null) {
    const p = playPromise;
    playPromise = null;
    return p.then(
      () => { audio.pause(); },
      ()  => { /* AbortError from a previous src-change — safe */ }
    );
  }
  audio.pause();
  return Promise.resolve();
}

/* ═══════════════════════════════════════════════════
   AUDIO EVENT LISTENERS
═══════════════════════════════════════════════════ */
function bindAudioEvents() {
  /* ── loadstart: a new src is being fetched ── */
  audio.addEventListener('loadstart', () => {
    /* Do NOT reset tTot here — loadTrack() already set the static
       duration string, and loadedmetadata will update it to the real
       value once the browser reads the file header.
       Zeroing it here creates a visible flash back to "0:00". */
    resetProgress();
  });

  /* ── waiting: buffering mid-playback ── */
  audio.addEventListener('waiting', () => {
    setLoadingState(true);
  });

  /* ── canplay: enough data to start (or resume) ── */
  audio.addEventListener('canplay', () => {
    setLoadingState(false);
  });

  /* ── canplaythrough: full buffer expected ── */
  audio.addEventListener('canplaythrough', () => {
    setLoadingState(false);
  });

  /* ── loadedmetadata: real duration available ── */
  audio.addEventListener('loadedmetadata', () => {
    /* Guard: ignore if this event belongs to an old track */
    const gen = audio._ehsaasGen;
    if (gen !== trackGen) return;

    const dur = audio.duration;
    if (tTot && dur && isFinite(dur) && !isNaN(dur)) {
      tTot.textContent = fmt(dur);
    }
  });

  /* ── timeupdate: playback position changed ── */
  audio.addEventListener('timeupdate', () => {
    if (isDragging) return;
    const dur = audio.duration;
    if (!dur || isNaN(dur) || !isFinite(dur)) return;
    const ratio = audio.currentTime / dur;
    updateProgressUI(ratio);
    if (tCur) tCur.textContent = fmt(audio.currentTime);
  });

  /* ── play: browser confirmed playback started ── */
  audio.addEventListener('play', () => {
    setUIPlaying(true);
  });

  /* ── pause: browser confirmed playback paused ── */
  audio.addEventListener('pause', () => {
    setUIPlaying(false);
  });

  /* ── ended: track finished naturally ── */
  audio.addEventListener('ended', () => {
    /* Guard: ignore if this event belongs to an old track */
    const gen = audio._ehsaasGen;
    if (gen !== trackGen) return;
    handleTrackEnded();
  });

  /* ── error: never swallow ── */
  audio.addEventListener('error', () => {
    /* Guard: ignore if this event belongs to an old track */
    const gen = audio._ehsaasGen;
    if (gen !== trackGen) return;
    setLoadingState(false);
    handleAudioError();
  });
}

/* ═══════════════════════════════════════════════════
   LOAD A TRACK
   ① Cancels any in-flight play() Promise cleanly
   ② Bumps the generation counter
   ③ Stamps the new gen onto the audio element
      (so event handlers can check it)
   ④ Sets the new src and calls load()
   ⑤ Optionally starts playback
═══════════════════════════════════════════════════ */
function loadTrack(idx, autoplay) {
  /* ── Defensive: validate index ── */
  if (!TRACKS || TRACKS.length === 0) {
    showToast('⚠️ No tracks in this theme yet');
    return;
  }
  if (typeof idx !== 'number' || idx < 0 || idx >= TRACKS.length) {
    console.warn(`Ehsaas: loadTrack() called with invalid index ${idx}`);
    return;
  }

  const t = TRACKS[idx];
  if (!t) {
    console.warn(`Ehsaas: track at index ${idx} is undefined`);
    return;
  }

  /* ── Stop any in-flight play() cleanly ── */
  waitForPause();

  /* ── Bump generation so old events are ignored ── */
  trackGen += 1;
  audio._ehsaasGen = trackGen;   // stamp the element

  currentIdx = idx;

  /* ── Update UI metadata immediately ── */
  if (tName) tName.textContent = t.name;
  /* Show artist only when it's not empty */
  if (tArt)  tArt.textContent  = t.artist || t.name;
  if (aImg)  aImg.src          = t.thumb || '';
  if (tTot)  tTot.textContent  = t.duration;   // static until metadata loads
  if (tCur)  tCur.textContent  = '0:00';
  resetProgress();
  syncMainLike();
  markActiveTrack();
  updateRepeatUI();

  /* ── Guard: empty src ── */
  if (!t.src || t.src.trim() === '') {
    showMissingAudioError(t.name);
    setUIPlaying(false);
    setLoadingState(false);
    return;
  }

  /* ── Set source and load ── */
  setLoadingState(true);
  audio.src = t.src;
  audio.load();   // resets the element, triggers loadstart

  if (autoplay) {
    startPlayback();
  } else {
    setUIPlaying(false);
  }
}

/* ═══════════════════════════════════════════════════
   START PLAYBACK
   Prevents a second play() call while one is already
   in-flight (rapid-click safety).
═══════════════════════════════════════════════════ */
function startPlayback() {
  /* ── Defensive: no audio element ── */
  if (!audio) {
    console.error('Ehsaas: startPlayback() — audio element missing');
    return;
  }

  /* ── Prevent stacking multiple play() calls ── */
  if (playPromise !== null) {
    /* A play() is already in-flight — don't stack another */
    return;
  }

  /* ── Defensive: no src set ── */
  if (!audio.src || audio.src === window.location.href) {
    const t = TRACKS[currentIdx];
    if (!t || !t.src) {
      showMissingAudioError(t ? t.name : 'Unknown');
      return;
    }
    audio.src = t.src;
    audio.load();
  }

  const myGen = trackGen;   // capture gen at call time

  playPromise = audio.play();

  playPromise
    .then(() => {
      playPromise = null;
      /* Stale: a newer track was loaded before this resolved */
      if (myGen !== trackGen) return;
      setLoadingState(false);
    })
    .catch((err) => {
      playPromise = null;
      /* Stale resolve — discard */
      if (myGen !== trackGen) return;

      setLoadingState(false);

      /* AbortError: src changed mid-play — safe, not a user-facing error */
      if (err.name === 'AbortError') return;

      /* NotAllowedError: browser blocked autoplay before user gesture */
      if (err.name === 'NotAllowedError') {
        showToast('▶ Tap Play to start — browser requires a tap first');
        setUIPlaying(false);
        return;
      }

      /* NotSupportedError: file not found or format unsupported */
      if (err.name === 'NotSupportedError') {
        showMissingAudioError(TRACKS[currentIdx]?.name ?? 'Unknown');
        setUIPlaying(false);
        return;
      }

      /* All other errors — show user-friendly message, not raw browser text */
      showToast('Unable to play this track.');
      setUIPlaying(false);
    });
}

/* ═══════════════════════════════════════════════════
   togglePlay — called by the Play button
═══════════════════════════════════════════════════ */
function togglePlay() {
  if (!audio) return;

  if (!TRACKS || TRACKS.length === 0) {
    showToast('⚠️ No tracks in this theme yet');
    return;
  }

  const t = TRACKS[currentIdx];
  if (!t) return;

  if (!t.src || t.src.trim() === '') {
    showMissingAudioError(t.name);
    return;
  }

  if (isPlaying) {
    /* Safely pause — wait for any in-flight play() first */
    waitForPause();
  } else {
    /* If no src loaded yet (fresh page load), set it */
    if (!audio.src || audio.src === window.location.href) {
      setLoadingState(true);
      audio.src = t.src;
      audio.load();
    }
    startPlayback();
  }
}

/* ═══════════════════════════════════════════════════
   TRACK ENDED HANDLER
═══════════════════════════════════════════════════ */
function handleTrackEnded() {
  setLoadingState(false);

  if (repeatMode === 2) {
    audio.currentTime = 0;
    startPlayback();
    return;
  }

  if (queue.length) {
    const qid = queue.shift();
    const qi  = TRACKS.findIndex(t => t.id === qid);
    if (qi !== -1) { loadTrack(qi, true); renderQueue(); return; }
  }

  if (repeatMode === 1) {
    loadTrack((currentIdx + 1) % TRACKS.length, true);
    return;
  }

  if (currentIdx >= TRACKS.length - 1) {
    setUIPlaying(false);
    resetProgress();
    if (tCur) tCur.textContent = '0:00';
    return;
  }

  loadTrack(currentIdx + 1, true);
}

/* ═══════════════════════════════════════════════════
   AUDIO ERROR HANDLER
   Maps MediaError codes → user-friendly messages.
   Never exposes raw browser error text unless useful.
   Never auto-skips — user sees the error and decides.
═══════════════════════════════════════════════════ */
function handleAudioError() {
  setUIPlaying(false);

  const err   = audio ? audio.error : null;
  const track = TRACKS[currentIdx];
  const name  = track ? track.name : 'this track';

  if (!err) {
    /* error event fired but no MediaError object (rare) */
    showToast(`Unable to play "${name}".`);
    return;
  }

  switch (err.code) {
    case MediaError.MEDIA_ERR_ABORTED:
      /*
       * MEDIA_ERR_ABORTED (1): playback aborted by the user agent
       * or by a src change — this is an expected internal event,
       * not a real failure visible to the user.
       */
      break;

    case MediaError.MEDIA_ERR_NETWORK:
      /*
       * MEDIA_ERR_NETWORK (2): a network failure stopped the download
       * mid-stream (file exists but connection dropped / timed out).
       */
      showToast(`Unable to play this track — check your connection.`);
      break;

    case MediaError.MEDIA_ERR_DECODE:
      /*
       * MEDIA_ERR_DECODE (3): file downloaded but the browser's
       * decoder failed — usually a corrupt or partially-written file.
       */
      showToast(`Unable to play "${name}" — the file may be corrupt.`);
      break;

    case MediaError.MEDIA_ERR_SRC_NOT_SUPPORTED:
      /*
       * MEDIA_ERR_SRC_NOT_SUPPORTED (4): file not found (404),
       * unsupported audio format, or empty src.
       */
      showMissingAudioError(name);
      break;

    default:
      showToast(`Unable to play "${name}".`);
  }
}

function showMissingAudioError(trackName) {
  showToast(`📁 "${trackName}" not found — place its MP3 in audio/${currentThemeId}/`);
}

/* ═══════════════════════════════════════════════════
   LOADING STATE
   Adds/removes a CSS class on the disc and play button
   to show a spinner while audio is buffering.
   Uses the existing #albumArt and #playBtn elements;
   the CSS class 'loading' drives the visual.
═══════════════════════════════════════════════════ */
function setLoadingState(loading) {
  isLoadingAudio = loading;
  if (aDisc)  aDisc.classList.toggle('loading', loading);
  if (playBtn) playBtn.classList.toggle('loading', loading);
}

/* ═══════════════════════════════════════════════════
   PREVIOUS / NEXT
═══════════════════════════════════════════════════ */
function prevTrack() {
  if (!TRACKS || TRACKS.length === 0) return;
  /* If more than 3 s played, restart current track */
  if (audio && audio.currentTime > 3) {
    audio.currentTime = 0;
    if (!isPlaying) startPlayback();
    return;
  }
  const prev = currentIdx > 0 ? currentIdx - 1 : TRACKS.length - 1;
  loadTrack(prev, isPlaying);
}

function nextTrack() {
  if (!TRACKS || TRACKS.length === 0) return;

  if (queue.length) {
    const qid = queue.shift();
    const qi  = TRACKS.findIndex(t => t.id === qid);
    if (qi !== -1) { loadTrack(qi, true); renderQueue(); return; }
  }

  let next;
  if (isShuffle) {
    if (TRACKS.length === 1) { next = 0; }
    else {
      do { next = Math.floor(Math.random() * TRACKS.length); }
      while (next === currentIdx);
    }
  } else {
    next = (currentIdx + 1) % TRACKS.length;
  }
  loadTrack(next, isPlaying);
}

/* ═══════════════════════════════════════════════════
   SEEK
   Guards against seeking before duration is known.
═══════════════════════════════════════════════════ */
function seekTrack(e) {
  if (!audio) return;
  const dur = audio.duration;
  if (!dur || isNaN(dur) || !isFinite(dur)) return;   // not ready yet
  const r = clickRatio(e.clientX, pBar);
  audio.currentTime = r * dur;
  updateProgressUI(r);
  if (tCur) tCur.textContent = fmt(audio.currentTime);
}

function clickRatio(clientX, el) {
  if (!el) return 0;
  const rect = el.getBoundingClientRect();
  return Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
}

/* ── Progress-bar drag (mouse + touch) ── */
function bindProgressDrag() {
  if (!pBar) return;

  pBar.addEventListener('mousedown', (e) => {
    isDragging = true;
    seekTrack(e);
  });
  document.addEventListener('mousemove', (e) => {
    if (!isDragging) return;
    const r   = clickRatio(e.clientX, pBar);
    const dur = audio ? audio.duration : NaN;
    updateProgressUI(r);
    if (dur && isFinite(dur) && !isNaN(dur)) {
      audio.currentTime   = r * dur;
      if (tCur) tCur.textContent = fmt(audio.currentTime);
    }
  });
  document.addEventListener('mouseup', () => { isDragging = false; });

  pBar.addEventListener('touchstart', (e) => {
    isDragging = true;
    const r   = clickRatio(e.touches[0].clientX, pBar);
    const dur = audio ? audio.duration : NaN;
    updateProgressUI(r);
    if (dur && isFinite(dur) && !isNaN(dur)) audio.currentTime = r * dur;
  }, { passive: true });

  pBar.addEventListener('touchmove', (e) => {
    const r   = clickRatio(e.touches[0].clientX, pBar);
    const dur = audio ? audio.duration : NaN;
    updateProgressUI(r);
    if (dur && isFinite(dur) && !isNaN(dur)) {
      audio.currentTime = r * dur;
      if (tCur) tCur.textContent = fmt(audio.currentTime);
    }
  }, { passive: true });

  pBar.addEventListener('touchend', () => { isDragging = false; });
}

/* ═══════════════════════════════════════════════════
   VOLUME / MUTE
═══════════════════════════════════════════════════ */
function setVolume(v) {
  if (!audio) return;
  volume       = Math.max(0, Math.min(1, parseFloat(v)));
  audio.volume = volume;

  if (volSlider && Math.abs(parseFloat(volSlider.value) / 100 - volume) > 0.01) {
    volSlider.value = Math.round(volume * 100);
  }

  if (volume > 0 && isMuted) {
    isMuted     = false;
    audio.muted = false;
    updateMuteUI();
  }

  updateVolWaves();
}

function toggleMute() {
  if (!audio) return;
  isMuted     = !isMuted;
  audio.muted = isMuted;
  updateMuteUI();
  showToast(isMuted ? '🔇 Muted' : '🔊 Unmuted');
}

function updateMuteUI() {
  if (!muteBtn) return;
  muteBtn.classList.toggle('muted', isMuted);
  updateVolWaves();
}

function updateVolWaves() {
  if (!muteIco) return;
  if (isMuted || volume === 0) {
    muteIco.innerHTML = `
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/>
      <line x1="23" y1="9" x2="17" y2="15" stroke="currentColor" stroke-width="2"/>
      <line x1="17" y1="9" x2="23" y2="15" stroke="currentColor" stroke-width="2"/>`;
  } else if (volume < 0.5) {
    muteIco.innerHTML = `
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/>
      <path id="volWave2" d="M15.54 8.46a5 5 0 0 1 0 7.07"/>`;
  } else {
    muteIco.innerHTML = `
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/>
      <path id="volWave1" d="M19.07 4.93a10 10 0 0 1 0 14.14"/>
      <path id="volWave2" d="M15.54 8.46a5 5 0 0 1 0 7.07"/>`;
  }
}

/* ═══════════════════════════════════════════════════
   SHUFFLE / REPEAT
═══════════════════════════════════════════════════ */
function toggleShuffle() {
  isShuffle = !isShuffle;
  if (shufBtn) shufBtn.classList.toggle('active', isShuffle);
  showToast(isShuffle ? '🔀 Shuffle on' : '🔀 Shuffle off');
}

function toggleRepeat() {
  repeatMode = (repeatMode + 1) % 3;
  updateRepeatUI();
  const labels = ['🔁 Repeat off', '🔁 Repeat all', '🔂 Repeat one'];
  showToast(labels[repeatMode]);
}

function updateRepeatUI() {
  if (!repeatBtn) return;
  repeatBtn.classList.toggle('active',     repeatMode > 0);
  repeatBtn.classList.toggle('repeat-one', repeatMode === 2);
}

/* ═══════════════════════════════════════════════════
   LIKE
═══════════════════════════════════════════════════ */
function toggleLike() {
  if (!TRACKS || !TRACKS.length) return;
  const id = TRACKS[currentIdx]?.id;
  if (id === undefined) return;

  if (liked.has(id)) {
    liked.delete(id);
    showToast('💔 Removed from liked');
  } else {
    liked.add(id);
    showToast('❤️ Liked!');
    if (likeBtn) {
      likeBtn.style.transform = 'scale(1.4)';
      setTimeout(() => { likeBtn.style.transform = ''; }, 250);
    }
  }
  syncMainLike();
  syncTrackLikeUI(id);
}

function toggleTrkLike(e, id) {
  e.stopPropagation();
  const btn = e.currentTarget;
  const svg = btn.querySelector('svg');
  if (liked.has(id)) {
    liked.delete(id);
    btn.classList.remove('liked');
    if (svg) svg.setAttribute('fill', 'none');
  } else {
    liked.add(id);
    btn.classList.add('liked');
    if (svg) svg.setAttribute('fill', 'currentColor');
    showToast('❤️ Liked!');
  }
  if (TRACKS[currentIdx] && TRACKS[currentIdx].id === id) syncMainLike();
}

function syncMainLike() {
  if (!likeBtn || !TRACKS || !TRACKS.length) return;
  const isLiked = liked.has(TRACKS[currentIdx]?.id);
  likeBtn.classList.toggle('liked', isLiked);
  const svg = likeBtn.querySelector('svg');
  if (svg) {
    svg.setAttribute('fill',   isLiked ? 'currentColor' : 'none');
    svg.setAttribute('stroke', 'currentColor');
  }
}

function syncTrackLikeUI(id) {
  if (!trkList) return;
  const i = TRACKS.findIndex(t => t.id === id);
  if (i === -1) return;
  const row = trkList.querySelector(`.track-item:nth-child(${i + 1}) .ti-like`);
  if (!row) return;
  row.classList.toggle('liked', liked.has(id));
  const svg = row.querySelector('svg');
  if (svg) svg.setAttribute('fill', liked.has(id) ? 'currentColor' : 'none');
}

/* ═══════════════════════════════════════════════════
   QUEUE
═══════════════════════════════════════════════════ */
function addQ(e, id) {
  e.stopPropagation();
  queue.push(id);
  renderQueue();
  showToast('➕ Added to queue');
  const btn = e.currentTarget;
  const originalText = btn.textContent;
  btn.textContent = '✓';
  btn.style.cssText = 'background:var(--ac);border-color:var(--ac);color:#fff';
  setTimeout(() => {
    btn.textContent   = originalText;
    btn.style.cssText = '';
  }, 1000);
}

function renderQueue() {
  if (!qCnt || !qList || !qEmpty) return;
  qCnt.textContent = queue.length;

  qList.querySelectorAll('.queue-item').forEach(el => el.remove());

  if (!queue.length) {
    qEmpty.style.display = 'block';
    return;
  }
  qEmpty.style.display = 'none';

  queue.forEach((tid, qi) => {
    const t = TRACKS.find(x => x.id === tid);
    if (!t) return;
    const el = document.createElement('div');
    el.className = 'queue-item';
    el.style.animationDelay = `${qi * 0.05}s`;
    el.innerHTML = `
      <div class="qi-thumb"><img src="${t.thumb}" alt="" loading="lazy"/></div>
      <div class="qi-info">
        <span class="qi-name">${t.name}</span>
        <span class="qi-artist">${t.artist}</span>
      </div>
      <button class="qi-rm" onclick="rmQ(${qi})" title="Remove">×</button>`;
    qList.appendChild(el);
  });
}

function rmQ(i) {
  queue.splice(i, 1);
  renderQueue();
}

function clearQueue() {
  queue = [];
  renderQueue();
  showToast('🗑️ Queue cleared');
}

function toggleQueue() {
  if (!qSec) return;
  queueOpen = !queueOpen;
  qSec.classList.toggle('open', queueOpen);
  /* Rotate the chevron to indicate open/closed state */
  const chev = document.getElementById('queueChevron');
  if (chev) chev.textContent = queueOpen ? '▾' : '▸';
  if (queueOpen) qSec.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

/* ═══════════════════════════════════════════════════
   PLAY ALL / SHUFFLE ALL
═══════════════════════════════════════════════════ */
function playAll() {
  if (!TRACKS || !TRACKS.length) { showToast('⚠️ No tracks in this theme yet'); return; }
  isShuffle = false;
  if (shufBtn) shufBtn.classList.remove('active');
  loadTrack(0, true);
}

function shuffleAll() {
  if (!TRACKS || !TRACKS.length) { showToast('⚠️ No tracks in this theme yet'); return; }
  isShuffle = true;
  if (shufBtn) shufBtn.classList.add('active');
  loadTrack(Math.floor(Math.random() * TRACKS.length), true);
  showToast('🔀 Shuffle on!');
}

function selectTrack(i) {
  loadTrack(i, true);
}

/* ═══════════════════════════════════════════════════
   THEME SYSTEM
═══════════════════════════════════════════════════ */
function loadThemeTracks(themeId) {
  /* Stop playback cleanly before switching */
  waitForPause();
  if (audio) audio.src = '';

  currentThemeId = themeId;
  TRACKS     = (THEME_TRACKS[themeId] || []).slice();
  currentIdx = 0;
  queue      = [];
  isPlaying  = false;

  setUIPlaying(false);
  setLoadingState(false);
  resetProgress();
  if (tCur) tCur.textContent = '0:00';
  if (tTot) tTot.textContent = '0:00';
  renderTracks();
  renderQueue();

  if (TRACKS.length) {
    loadTrack(0, false);
  } else {
    if (tName)  tName.textContent  = 'No songs yet';
    if (tArt)   tArt.textContent   = `Add MP3s to audio/${themeId}/`;
    if (aImg)   aImg.src           = 'bg1.png';
    if (trkCnt) trkCnt.textContent = '0 songs';
  }
}

function setTheme(id) {
  const th = THEMES.find(t => t.id === id);
  if (!th) return;
  themeIdx = THEMES.indexOf(th);

  document.body.setAttribute('data-theme', id);
  if (tgIco) tgIco.textContent = th.icon;
  if (tgLbl) tgLbl.textContent = th.label;

  if (hTitle) {
    hTitle.style.cssText = 'opacity:0;transform:translateY(8px)';
  }
  if (hSub) hSub.style.opacity = '0';

  setTimeout(() => {
    if (hTitle) {
      hTitle.textContent = th.title;
      const isPriyanka   = id === 'priyanka';
      hTitle.style.cssText = `transition:opacity .4s,transform .4s;opacity:1;transform:translateY(0);${isPriyanka ? 'color:#6b6b6b;' : ''}`;
    }
    if (hSub) {
      hSub.textContent = th.sub;
      const isPriyanka = id === 'priyanka';
      hSub.style.cssText = `transition:opacity .4s;opacity:1;${isPriyanka ? 'color:rgba(90,90,90,.85);' : ''}`;
    }
  }, 160);

  if (heroBg) {
    heroBg.classList.add('fading');
    setTimeout(() => heroBg.classList.remove('fading'), 700);
  }

  /* Re-fetch tracks so any newly added files appear immediately */
  fetchTracks().then(() => {
    loadThemeTracks(id);
  });

  closeTheme();
  syncThemeActive();
  showToast(`${th.icon} ${th.label}`);
}

function cycleTheme() {
  if (!tgDrop) return;
  tgDrop.classList.contains('open') ? closeTheme() : openTheme();
}
function openTheme() {
  if (!tgDrop || !tgBtn) return;
  tgDrop.classList.add('open');
  tgBtn.classList.add('open');
  setTimeout(() => document.addEventListener('click', outsideTheme), 55);
}
function closeTheme() {
  if (!tgDrop || !tgBtn) return;
  tgDrop.classList.remove('open');
  tgBtn.classList.remove('open');
  document.removeEventListener('click', outsideTheme);
}
function outsideTheme(e) {
  if (!e.target.closest('.theme-switcher')) closeTheme();
}
function syncThemeActive() {
  const cur = document.body.getAttribute('data-theme');
  document.querySelectorAll('.t-opt').forEach(o => {
    o.classList.toggle('active', o.dataset.theme === cur);
  });
}

/* ═══════════════════════════════════════════════════
   RENDER TRACK LIST
═══════════════════════════════════════════════════ */
function renderTracks() {
  if (!trkList) return;
  trkList.innerHTML = '';
  if (trkCnt) trkCnt.textContent = `${TRACKS.length} song${TRACKS.length !== 1 ? 's' : ''}`;

  if (!TRACKS.length) {
    trkList.innerHTML = `<p style="color:var(--t3);font-size:12px;font-style:italic;
      padding:20px 0;text-align:center;">
      No songs in this theme yet.<br>
      Add MP3 files to <code>audio/${currentThemeId}/</code>
    </p>`;
    return;
  }

  TRACKS.forEach((t, i) => {
    const isActive = i === currentIdx;
    const isLiked  = liked.has(t.id);
    const el       = document.createElement('div');
    el.className   = `track-item${isActive ? ' active' : ''}`;
    el.dataset.i   = i;
    el.style.animationDelay = `${i * 0.038}s`;
    el.innerHTML = `
      <div class="ti-num">${i + 1}</div>
      <div class="ti-thumb"><img src="${t.thumb}" alt="" loading="lazy"/></div>
      <div class="ti-info">
        <span class="ti-name">${t.name}</span>
        <span class="ti-artist">${t.artist || '&nbsp;'}</span>
      </div>
      <div class="ti-badge">
        <svg width="8" height="8" viewBox="0 0 24 24" fill="currentColor">
          <rect x="2" y="5"  width="3" height="14" rx="1"/>
          <rect x="10" y="3" width="3" height="18" rx="1"/>
          <rect x="18" y="7" width="3" height="10" rx="1"/>
        </svg>Playing
      </div>
      <span class="ti-dur">${t.duration}</span>
      <button class="ti-like${isLiked ? ' liked' : ''}"
              onclick="toggleTrkLike(event, ${t.id})" title="Like">
        <svg viewBox="0 0 24 24"
             fill="${isLiked ? 'currentColor' : 'none'}"
             stroke="currentColor" stroke-width="2">
          <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67
                   l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06
                   L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
        </svg>
      </button>
      <button class="ti-add" onclick="addQ(event, ${t.id})" title="Add to queue">+</button>
    `;
    el.addEventListener('click', (e) => {
      if (e.target.closest('.ti-like') || e.target.closest('.ti-add')) return;
      selectTrack(i);
    });
    trkList.appendChild(el);
  });
}

function markActiveTrack() {
  if (!trkList) return;
  document.querySelectorAll('.track-item').forEach((el, i) => {
    el.classList.toggle('active', i === currentIdx);
  });
}

/* ═══════════════════════════════════════════════════
   UI STATE HELPERS
═══════════════════════════════════════════════════ */
function setUIPlaying(p) {
  isPlaying = p;
  if (!playBtn || !playIco) return;

  if (p) {
    playBtn.classList.add('playing');
    playIco.setAttribute('fill', 'currentColor');
    playIco.innerHTML = `
      <rect x="6"  y="4" width="4" height="16" rx="1"/>
      <rect x="14" y="4" width="4" height="16" rx="1"/>`;
    if (aDisc) {
      aDisc.classList.add('spinning');
      aDisc.classList.remove('paused');
    }
  } else {
    playBtn.classList.remove('playing');
    playIco.setAttribute('fill', 'currentColor');
    playIco.innerHTML = '<polygon points="5 3 19 12 5 21 5 3"/>';
    if (aDisc) {
      aDisc.classList.remove('spinning');
      aDisc.classList.add('paused');
    }
  }
}

function updateProgressUI(ratio) {
  if (!pFill || !pDot) return;
  const pct = (ratio * 100).toFixed(2) + '%';
  pFill.style.width = pct;
  pDot.style.left   = pct;
}

function resetProgress() {
  updateProgressUI(0);
}

function fmt(seconds) {
  if (seconds === undefined || seconds === null) return '0:00';
  if (isNaN(seconds) || !isFinite(seconds))      return '0:00';
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, '0')}`;
}

/* ═══════════════════════════════════════════════════
   TOAST — reuses existing pattern, no redesign
═══════════════════════════════════════════════════ */
let toastTimer;
function showToast(msg) {
  let el = document.getElementById('_toast');
  if (!el) {
    el = document.createElement('div');
    el.id = '_toast';
    el.style.cssText = [
      'position:fixed',
      'bottom:112px',
      'left:50%',
      'transform:translateX(-50%) translateY(14px)',
      'background:var(--glass)',
      'border:1px solid var(--gb)',
      'color:var(--t1)',
      "font-family:'Nunito',sans-serif",
      'font-size:11px',
      'font-weight:800',
      'padding:7px 16px',
      'border-radius:50px',
      'backdrop-filter:blur(20px)',
      '-webkit-backdrop-filter:blur(20px)',
      'z-index:9999',
      'opacity:0',
      'transition:opacity .2s,transform .2s',
      'pointer-events:none',
      'white-space:nowrap',
      'box-shadow:0 4px 16px rgba(0,0,0,.35)',
    ].join(';');
    document.body.appendChild(el);
  }
  el.textContent = msg;
  el.style.opacity   = '1';
  el.style.transform = 'translateX(-50%) translateY(0)';
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => {
    el.style.opacity   = '0';
    el.style.transform = 'translateX(-50%) translateY(14px)';
  }, 2500);
}

/* ═══════════════════════════════════════════════════
   KEYBOARD SHORTCUTS
═══════════════════════════════════════════════════ */
function bindKeyboard() {
  document.addEventListener('keydown', (e) => {
    if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;

    switch (e.code) {
      case 'Space':
        e.preventDefault();
        togglePlay();
        break;
      case 'ArrowRight':
        e.preventDefault();
        if (e.shiftKey) {
          if (audio && audio.duration && isFinite(audio.duration)) {
            audio.currentTime = Math.min(audio.duration, audio.currentTime + 10);
          }
        } else {
          nextTrack();
        }
        break;
      case 'ArrowLeft':
        e.preventDefault();
        if (e.shiftKey) {
          if (audio) audio.currentTime = Math.max(0, audio.currentTime - 10);
        } else {
          prevTrack();
        }
        break;
      case 'ArrowUp':
        e.preventDefault();
        setVolume(volume + 0.1);
        if (volSlider) volSlider.value = Math.round(volume * 100);
        showToast(`🔊 ${Math.round(volume * 100)}%`);
        break;
      case 'ArrowDown':
        e.preventDefault();
        setVolume(volume - 0.1);
        if (volSlider) volSlider.value = Math.round(volume * 100);
        showToast(`🔉 ${Math.round(volume * 100)}%`);
        break;
      case 'KeyM': toggleMute();   break;
      case 'KeyS': toggleShuffle(); break;
      case 'KeyR': toggleRepeat();  break;
      case 'KeyL': toggleLike();    break;
      case 'KeyT':
        themeIdx = (themeIdx + 1) % THEMES.length;
        setTheme(THEMES[themeIdx].id);
        break;
    }
  });
}

/* ═══════════════════════════════════════════════════
   PARALLAX
═══════════════════════════════════════════════════ */
function bindParallax() {
  window.addEventListener('scroll', () => {
    const hero = document.getElementById('hero');
    if (!hero || !heroBg) return;
    const sy = window.scrollY;
    if (sy < hero.offsetHeight) {
      heroBg.style.transform = `scale(1.04) translateY(${sy * 0.2}px)`;
    }
  }, { passive: true });
}

/* ═══════════════════════════════════════════════════
   BOOT
═══════════════════════════════════════════════════ */
document.addEventListener('DOMContentLoaded', init);
